apiVersion: v1
kind: PersistentVolume
metadata:
  name: craftingwiththesquad-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/ftb-server-files/backups"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: craftingwiththesquad-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi